/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vedantanew;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author boss
 */
public class BillDisplay extends javax.swing.JPanel {
DefaultTableModel dtm ;
Connection conn;
Statement stmt;
    /**
     * Creates new form BillPrint
     */
    public BillDisplay() {
        initComponents();
        String col[] = {"Product","Qty","Rate","Total"};
        dtm = new DefaultTableModel(col,0);
        displayTable.setModel(dtm);
        resetBill();
        conn = DBHelper.initConnection();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        billNoLabel = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        errorPanel = new javax.swing.JPanel();
        errorLabel = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        printButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        gqtyLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gTotalLabel = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(java.awt.Color.darkGray);

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Name :");

        cityLabel.setForeground(java.awt.Color.white);
        cityLabel.setText("No City");

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Bill No :");

        dateLabel.setForeground(java.awt.Color.white);
        dateLabel.setText("No Date");

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("City :");

        nameLabel.setForeground(java.awt.Color.white);
        nameLabel.setText("No Name");

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Date :");

        billNoLabel.setForeground(java.awt.Color.white);
        billNoLabel.setText("No Bill");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(billNoLabel))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(nameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cityLabel)))
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(billNoLabel)
                    .addComponent(jLabel4)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nameLabel)
                    .addComponent(jLabel8)
                    .addComponent(cityLabel))
                .addContainerGap())
        );

        mainPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Quantity", "Rate", "Total"
            }
        ));
        jScrollPane1.setViewportView(displayTable);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.BorderLayout());

        errorPanel.setBackground(java.awt.Color.darkGray);
        errorPanel.setMinimumSize(new java.awt.Dimension(1200, 30));
        errorPanel.setPreferredSize(new java.awt.Dimension(1200, 30));
        errorPanel.setLayout(new javax.swing.BoxLayout(errorPanel, javax.swing.BoxLayout.LINE_AXIS));

        errorLabel.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        errorLabel.setForeground(java.awt.Color.white);
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText("Error Label");
        errorLabel.setMaximumSize(new java.awt.Dimension(1200, 20));
        errorLabel.setMinimumSize(new java.awt.Dimension(1200, 20));
        errorLabel.setPreferredSize(new java.awt.Dimension(1200, 20));
        errorPanel.add(errorLabel);

        bottomPanel.add(errorPanel, java.awt.BorderLayout.SOUTH);

        btnPanel.setBackground(java.awt.Color.darkGray);
        btnPanel.setMinimumSize(new java.awt.Dimension(1200, 42));
        btnPanel.setPreferredSize(new java.awt.Dimension(1200, 42));
        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        printButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        printButton.setText("Print");
        printButton.setPreferredSize(new java.awt.Dimension(100, 30));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        printButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printButtonKeyPressed(evt);
            }
        });
        btnPanel.add(printButton);

        editButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        editButton.setText("Edit");
        editButton.setPreferredSize(new java.awt.Dimension(100, 30));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        editButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editButtonKeyPressed(evt);
            }
        });
        btnPanel.add(editButton);

        deleteButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setPreferredSize(new java.awt.Dimension(100, 30));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        deleteButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deleteButtonKeyPressed(evt);
            }
        });
        btnPanel.add(deleteButton);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Total Quantity :");
        btnPanel.add(jLabel9);

        gqtyLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        gqtyLabel.setForeground(java.awt.Color.white);
        gqtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gqtyLabel.setText("0");
        gqtyLabel.setPreferredSize(new java.awt.Dimension(200, 28));
        btnPanel.add(gqtyLabel);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Grand Total :");
        btnPanel.add(jLabel10);

        gTotalLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        gTotalLabel.setForeground(java.awt.Color.white);
        gTotalLabel.setText("0");
        gTotalLabel.setPreferredSize(new java.awt.Dimension(200, 28));
        btnPanel.add(gTotalLabel);

        bottomPanel.add(btnPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(bottomPanel, java.awt.BorderLayout.SOUTH);

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deleteButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        delete();
    }//GEN-LAST:event_deleteButtonKeyPressed

    private void printButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        try {
            printReport();
        } catch (SQLException ex) {
            Logger.getLogger(BillDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printButtonKeyPressed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
    try {
        // TODO add your handling code here:
        printReport();
    } catch (SQLException ex) {
        Logger.getLogger(BillDisplay.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_printButtonActionPerformed

    void editBill(String billNum)
    {
        String[] options = {"YES","NO"};
        int dialogButton = JOptionPane.showOptionDialog(null,"Sure You Want to Edit Bill Num " + billNum, "Edit Bill", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE,null,options,options[1]); 
        if(dialogButton == JOptionPane.YES_OPTION)
        {
            try {
                int billNo = Integer.parseInt(billNum);
                conn = DBHelper.initConnection();
                stmt = conn.createStatement();
                String query = "Select * from transactions where billNo ="+ billNo;
                ResultSet executeQuery = stmt.executeQuery(query);
                if(executeQuery.first())
                {
                    Biller biller = new Biller(billNo);
                    this.add("editBill",biller);
                    CardLayout cl = (CardLayout)(this.getLayout());
                    cl.show(this, "editBill");
                }
                else
                {
                    String[] options1 = {"OK"};
                    JOptionPane.showMessageDialog(null,"Bill Number "+ billNum +" Not Exists ", "Bill Not Found", JOptionPane.ERROR_MESSAGE,null);
                }
                
                
            } catch (SQLException ex) {
                Logger.getLogger(BillDisplay.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
        }
    }
    private void editButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editButtonKeyPressed
        // TODO add your handling code here:
                if(evt.getKeyCode() == KeyEvent.VK_ENTER)
                    editBill(billNoLabel.getText());
    }//GEN-LAST:event_editButtonKeyPressed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        editBill(billNoLabel.getText());
    }//GEN-LAST:event_editButtonActionPerformed
public boolean showBill(int billNum)
    {
     
    conn = DBHelper.getConnection();
    boolean billExists = true;
    try 
    {    
        stmt = conn.createStatement();
    } 
    catch (SQLException ex) 
    {
        Logger.getLogger(BillDisplay.class.getName()).log(Level.SEVERE, null, ex);
    }
    String query = "select * from billEntry where billno ="+billNum;
      
    ResultSet executeQuery = null;
    try 
    {
            executeQuery = stmt.executeQuery(query);
    } 
    catch (SQLException ex) 
    {
            return false;

    }
     if(billExists)
        {
            int count = 0;
            try {
                String data[] = new String[4];
                while(executeQuery.next())
                {
                    count++;
                    data[0] = executeQuery.getString("pname");
                    data[1] = executeQuery.getString("qty");
                    data[2] = executeQuery.getString("rate");
                    data[3] = executeQuery.getString("total");
                    dtm.insertRow(dtm.getRowCount(), data);

                }
                if(count == 0)
                    return false;
                executeQuery.close();
                query = "select * from transactions where billNo ="+billNum;
                executeQuery = stmt.executeQuery(query);
                if(executeQuery.first())
                {
                    billNoLabel.setText(billNum +"");
                    nameLabel.setText(executeQuery.getString("pname"));
                    cityLabel.setText(executeQuery.getString("pcity"));
                    gqtyLabel.setText(executeQuery.getString("gqty"));
                    gTotalLabel.setText(executeQuery.getString("gtotal"));
                    SimpleDateFormat  sdf = new SimpleDateFormat("dd-MM-yyyy");
                    
                    dateLabel.setText( sdf.format(executeQuery.getDate("billDate")));
                }
                editButton.setEnabled(true);
                printButton.setEnabled(true);
                deleteButton.setEnabled(true);
            } catch (SQLException ex) {
                return false;
            }
        }
        
    return true;
    }
void resetBill()
{
    nameLabel.setText("No Name");
    cityLabel.setText("No City");
    dateLabel.setText("No Date");
    billNoLabel.setText("No Bill Num");
    dtm.setRowCount(0);
    gTotalLabel.setText("0");
    gqtyLabel.setText("0");
    errorLabel.setText("No Error At Present");
    editButton.setEnabled(false);
    printButton.setEnabled(false);
    deleteButton.setEnabled(false);
}
void printReport() throws SQLException
    {
        HashMap map = new HashMap();
        map.put("clientName", nameLabel.getText());
        map.put("clientCity", cityLabel.getText());
        map.put("billNo",billNoLabel.getText());
        map.put("billDate",dateLabel.getText());
        new BillPrint().showReport(map);
    }
    boolean delete(int billNum)
    {
        try {
                    String query = "delete from transactions where billNo = "+billNum;
                    stmt = conn.createStatement();
                    stmt.executeUpdate(query);
                    query = "delete from billEntry where billno ="+billNum;
                    stmt.executeUpdate(query);
                    return true;
            } catch (SQLException ex) {
                    errorLabel.setText("Deletion Problem");
                    Logger.getLogger(BillDisplay.class.getName()).log(Level.SEVERE, null, ex);
                    return false;
                }
    }
    void delete()
    {       
        String[] options = {"YES","NO"};
        String[] options1 = {"OK"};
        int dialogButton = JOptionPane.showOptionDialog(null,"Sure You Want to delete Bill Num " + billNoLabel.getText(), "Delete Bill", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE,null,options,options[1]);
           if(dialogButton == JOptionPane.YES_OPTION)
            {
                try {
                    String query = "delete from transactions where billNo = "+billNoLabel.getText();
                    stmt = conn.createStatement();
                    stmt.executeUpdate(query);
                    query = "delete from billEntry where billno ="+billNoLabel.getText();
                    stmt.executeUpdate(query);
                    dialogButton = JOptionPane.showOptionDialog(null,"Bill Deleted Successfully " , "Confirmation", JOptionPane.OK_OPTION,JOptionPane.INFORMATION_MESSAGE,null,options,options[0]);
                    resetBill();
                } catch (SQLException ex) {
                    errorLabel.setText("Deletion Problem");
                    Logger.getLogger(BillDisplay.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
                    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billNoLabel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable displayTable;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel errorPanel;
    private javax.swing.JLabel gTotalLabel;
    private javax.swing.JLabel gqtyLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
