/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vedantanew;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author boss
 */
public class HomePage extends javax.swing.JFrame {
    ClientManage clientManage;
    Biller biller;
    ProductManage productManage;
    SalesReport salesReport;
    Report report;
    BillDisplay billDisplay;
        /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        Rectangle maximumWindowBounds = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
        this.setSize(new Dimension(maximumWindowBounds.width, maximumWindowBounds.height));
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("Vedanta Mobile Solutions");
        mainCardPanel = new javax.swing.JPanel();
        mainCardPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainCardPanel, java.awt.BorderLayout.CENTER);
        biller = new Biller();
        mainCardPanel.add("estimate",biller);
        salesReport = new SalesReport();
        mainCardPanel.add("sales",salesReport);
        clientManage = new ClientManage();
        mainCardPanel.add("client", clientManage);
        productManage = new ProductManage();
        mainCardPanel.add("product",productManage);

     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mainCardPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        billingMenu = new javax.swing.JMenu();
        clientMenu = new javax.swing.JMenu();
        productMenu = new javax.swing.JMenu();
        sales = new javax.swing.JMenu();
        billManMenu = new javax.swing.JMenu();
        viewBillMenu = new javax.swing.JMenuItem();
        editBillMenu = new javax.swing.JMenuItem();
        deleteBillMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vedanta2.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setMinimumSize(new java.awt.Dimension(1200, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(1200, 50));
        jPanel1.add(jButton1, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ssdn.png"))); // NOI18N
        jButton2.setMinimumSize(new java.awt.Dimension(812, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(812, 40));
        jPanel1.add(jButton2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        mainCardPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainCardPanel, java.awt.BorderLayout.CENTER);

        billingMenu.setMnemonic('E');
        billingMenu.setText("Estimate");
        billingMenu.setMargin(new java.awt.Insets(0, 0, 0, 10));
        billingMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billingMenuMouseClicked(evt);
            }
        });
        billingMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                billingMenuMenuSelected(evt);
            }
        });
        billingMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                billingMenuKeyPressed(evt);
            }
        });
        jMenuBar1.add(billingMenu);

        clientMenu.setMnemonic('C');
        clientMenu.setText(" Manage Client");
        clientMenu.setMargin(new java.awt.Insets(0, 10, 0, 10));
        clientMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientMenuMouseClicked(evt);
            }
        });
        clientMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                clientMenuMenuSelected(evt);
            }
        });
        clientMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clientMenuKeyPressed(evt);
            }
        });
        jMenuBar1.add(clientMenu);

        productMenu.setMnemonic('P');
        productMenu.setText("Manage Product");
        productMenu.setToolTipText("");
        productMenu.setMargin(new java.awt.Insets(0, 10, 0, 10));
        productMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productMenuMouseClicked(evt);
            }
        });
        productMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                productMenuMenuSelected(evt);
            }
        });
        productMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productMenuKeyPressed(evt);
            }
        });
        jMenuBar1.add(productMenu);

        sales.setMnemonic('S');
        sales.setText("Sales");
        sales.setToolTipText("");
        sales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesMouseClicked(evt);
            }
        });
        sales.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                salesMenuSelected(evt);
            }
        });
        sales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salesKeyPressed(evt);
            }
        });
        jMenuBar1.add(sales);

        billManMenu.setMnemonic('B');
        billManMenu.setText("Manage Bills");
        billManMenu.setMargin(new java.awt.Insets(0, 10, 0, 0));

        viewBillMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        viewBillMenu.setText("View Bill");
        viewBillMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBillMenuMouseClicked(evt);
            }
        });
        viewBillMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBillMenuActionPerformed(evt);
            }
        });
        viewBillMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewBillMenuKeyPressed(evt);
            }
        });
        billManMenu.add(viewBillMenu);

        editBillMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        editBillMenu.setText("Edit Bill");
        editBillMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBillMenuMouseClicked(evt);
            }
        });
        editBillMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBillMenuActionPerformed(evt);
            }
        });
        editBillMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editBillMenuKeyPressed(evt);
            }
        });
        billManMenu.add(editBillMenu);

        deleteBillMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        deleteBillMenu.setText("Delete Bill");
        deleteBillMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBillMenuMouseClicked(evt);
            }
        });
        deleteBillMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBillMenuActionPerformed(evt);
            }
        });
        deleteBillMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deleteBillMenuKeyPressed(evt);
            }
        });
        billManMenu.add(deleteBillMenu);

        jMenuBar1.add(billManMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static boolean isInteger(String n) {
            try {
                    Integer.parseInt(n);
                    return true;
            } catch (NumberFormatException nfe) {
                    return false;
            }
        }
    private void editBillMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editBillMenuKeyPressed
        // TODO add your handling code here:
        {
            editBill();
        }
    }//GEN-LAST:event_editBillMenuKeyPressed

    private void deleteBillMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deleteBillMenuKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            deleteBill();
        }
    }//GEN-LAST:event_deleteBillMenuKeyPressed

    private void viewBillMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewBillMenuKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            viewBill();
        }
    }//GEN-LAST:event_viewBillMenuKeyPressed

    private void billingMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingMenuMouseClicked
        // TODO add your handling code here:
//        biller.loadClients();
//        biller.loadProducts();
//        System.out.println("Aaya");    
//        CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
//        cl.show(mainCardPanel, "estimate");
        
    }//GEN-LAST:event_billingMenuMouseClicked

    private void billingMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_billingMenuKeyPressed
        // TODO add your handling code here:
//        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
//        {
////            biller.loadClients();
////            biller.loadProducts();
////            CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
////            cl.show(mainCardPanel, "estimate");
//        }
    }//GEN-LAST:event_billingMenuKeyPressed

    private void clientMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientMenuMouseClicked
        // TODO add your handling code here:
//                CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
//                cl.show(mainCardPanel, "client");
    }//GEN-LAST:event_clientMenuMouseClicked

    private void clientMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientMenuKeyPressed
        // TODO add your handling code here:
//        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
//        {
//                CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
//                cl.show(mainCardPanel, "client");
//        }
    }//GEN-LAST:event_clientMenuKeyPressed

    private void productMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productMenuMouseClicked
        // TODO add your handling code here:
//                CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
//                cl.show(mainCardPanel, "product");
    }//GEN-LAST:event_productMenuMouseClicked

    private void productMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productMenuKeyPressed
        // TODO add your handling code here:
//        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
//        {
//                CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
//                cl.show(mainCardPanel, "product");
//        }
    }//GEN-LAST:event_productMenuKeyPressed

    private void salesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesMouseClicked
        // TODO add your handling code here:
//                CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
//                salesReport.updateClientList();
//                salesReport.resetLayout();
//                
//                cl.show(mainCardPanel, "sales");
                
    }//GEN-LAST:event_salesMouseClicked

    private void salesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salesKeyPressed
        // TODO add your handling code here:
//        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
//        {
//                CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
//                salesReport.resetLayout();
//                salesReport.updateClientList();
//                cl.show(mainCardPanel, "sales");
//        }
    }//GEN-LAST:event_salesKeyPressed

    void viewBill()
    {
        
        Object showInputDialog = JOptionPane.showInputDialog(null,"Enter Bill Number","View Bill",JOptionPane.QUESTION_MESSAGE);
        if(showInputDialog !=null)
        {
            if(isInteger(showInputDialog.toString()))
        {
            int billNum1 = Integer.parseInt(showInputDialog.toString());
            //System.out.println("View "+ billNum1);
            BillDisplay bd = new BillDisplay();
            bd.showBill(billNum1);
            mainCardPanel.add("viewBill",bd);
            CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
            cl.show(mainCardPanel,"viewBill");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Enter Proper Bill Number","Error", JOptionPane.ERROR_MESSAGE);
        }
        }
        
        
    }
    void editBill()
    {
        Object showInputDialog = JOptionPane.showInputDialog(null,"Enter Bill Number","Edit Bill",JOptionPane.QUESTION_MESSAGE);
        if(showInputDialog !=null)
        {
            int billNum1 = Integer.parseInt(showInputDialog.toString());
        if(isInteger(showInputDialog.toString()))
        {
            BillDisplay bd = new BillDisplay();
            bd.editBill(showInputDialog.toString());
            mainCardPanel.add("editBill",bd);
            CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
            cl.show(mainCardPanel,"editBill");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Enter Proper Bill Number","Error", JOptionPane.ERROR_MESSAGE);
        }
        }
        
        
    }
    void deleteBill()
    {
        Object showInputDialog = JOptionPane.showInputDialog(null,"Enter Bill Number","Delete Bill",JOptionPane.QUESTION_MESSAGE);
        if(showInputDialog !=null)
        {
         //   System.out.println("Delete Bill "+ showInputDialog.toString());
        int billNum1 = Integer.parseInt(showInputDialog.toString());
     //   System.out.println("Delete "+ billNum1);
//        
        BillDisplay bd = new BillDisplay();
        boolean delete = bd.delete(billNum1);
        if(delete)
        {
            JOptionPane.showMessageDialog(null,"Bill Num "+ billNum1 + " deleted successfully","Bill Deleted",JOptionPane.INFORMATION_MESSAGE);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Bill Num "+ billNum1 + " deletetion unsuccessfull","Bill Not Deleted",JOptionPane.ERROR_MESSAGE);
        }
        }
        
    }
    private void viewBillMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBillMenuMouseClicked
        // TODO add your handling code here:
                
    }//GEN-LAST:event_viewBillMenuMouseClicked

    private void editBillMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBillMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editBillMenuMouseClicked

    private void deleteBillMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBillMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBillMenuMouseClicked

    private void viewBillMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBillMenuActionPerformed
        // TODO add your handling code here:
        viewBill();
        
        
    }//GEN-LAST:event_viewBillMenuActionPerformed

    private void editBillMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBillMenuActionPerformed
        // TODO add your handling code here:
        editBill();
    }//GEN-LAST:event_editBillMenuActionPerformed

    private void deleteBillMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBillMenuActionPerformed
        // TODO add your handling code here:
        deleteBill();
        
    }//GEN-LAST:event_deleteBillMenuActionPerformed

    private void salesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_salesMenuSelected
        // TODO add your handling code here:
                        CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
                salesReport.resetLayout();
                salesReport.updateClientList();
                cl.show(mainCardPanel, "sales");
                salesReport.transactionAll.requestFocusInWindow();
    }//GEN-LAST:event_salesMenuSelected

    private void billingMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_billingMenuMenuSelected
        // TODO add your handling code here:
            biller.loadClients();
            biller.loadProducts();
            CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
            cl.show(mainCardPanel, "estimate");
    }//GEN-LAST:event_billingMenuMenuSelected

    private void clientMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_clientMenuMenuSelected
        // TODO add your handling code here:
                        CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
                cl.show(mainCardPanel, "client");
                clientManage.nameField.requestFocusInWindow();
    }//GEN-LAST:event_clientMenuMenuSelected

    private void productMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_productMenuMenuSelected
        // TODO add your handling code here:
                        CardLayout cl = (CardLayout)(mainCardPanel.getLayout());
                        cl.show(mainCardPanel, "product");
                        productManage.nameField.requestFocusInWindow();
    }//GEN-LAST:event_productMenuMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu billManMenu;
    private javax.swing.JMenu billingMenu;
    private javax.swing.JMenu clientMenu;
    private javax.swing.JMenuItem deleteBillMenu;
    private javax.swing.JMenuItem editBillMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainCardPanel;
    private javax.swing.JMenu productMenu;
    private javax.swing.JMenu sales;
    private javax.swing.JMenuItem viewBillMenu;
    // End of variables declaration//GEN-END:variables
}
