package vedantanew;


import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author boss
 */
public class SalesReport extends javax.swing.JPanel {
    private Connection conn;
    private Statement stmt;
    ClientReport report;
    Report report1;

    /**
     * Creates new form ProductManage
     */
    public SalesReport() {
      initComponents();
      conn = DBHelper.initConnection();
      updateClientList();
      
    }
    
        protected void updateClientList() {                                                    
        try {
            // TODO add your handling code here:
            String query = "select * from client order by name";
            stmt = conn.createStatement();
            ResultSet executeQuery = stmt.executeQuery(query);
            String client = "";
            clientList.removeAllItems();
            while(executeQuery.next())
            {
                client  = executeQuery.getString("name")+" ("+executeQuery.getString("city")+") "+executeQuery.getString("id");
                clientList.addItem(client);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ClientManage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        queryReport = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        transactionsPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        todayButton = new javax.swing.JButton();
        MonthButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fromDate = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        toDate = new javax.swing.JSpinner();
        rangeButton = new javax.swing.JButton();
        transactionAll = new javax.swing.JButton();
        clientViewPanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        clientList = new javax.swing.JComboBox();
        clientAll = new javax.swing.JButton();
        clientTodayButton = new javax.swing.JButton();
        clientMonthButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clientRangeButton = new javax.swing.JButton();
        toDate2 = new javax.swing.JSpinner();
        fromDate2 = new javax.swing.JSpinner();

        setMinimumSize(new java.awt.Dimension(1200, 480));
        setPreferredSize(new java.awt.Dimension(300, 300));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new java.awt.CardLayout());

        queryReport.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salesReport.png"))); // NOI18N
        queryReport.add(jButton1, java.awt.BorderLayout.PAGE_START);

        transactionsPanel.setBackground(java.awt.Color.darkGray);
        transactionsPanel.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 2, true));
        transactionsPanel.setMaximumSize(new java.awt.Dimension(675, 32767));
        transactionsPanel.setMinimumSize(new java.awt.Dimension(650, 480));
        transactionsPanel.setPreferredSize(new java.awt.Dimension(675, 480));
        transactionsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionsPanelMouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transactions.png"))); // NOI18N

        todayButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        todayButton.setText("Today ");
        todayButton.setMinimumSize(new java.awt.Dimension(200, 29));
        todayButton.setPreferredSize(new java.awt.Dimension(200, 29));
        todayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todayButtonMouseClicked(evt);
            }
        });
        todayButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                todayButtonKeyPressed(evt);
            }
        });

        MonthButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        MonthButton.setText("Month ");
        MonthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MonthButtonMouseClicked(evt);
            }
        });
        MonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthButtonActionPerformed(evt);
            }
        });
        MonthButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MonthButtonKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("From :");

        fromDate.setModel(new javax.swing.SpinnerDateModel());
        fromDate.setEditor(new javax.swing.JSpinner.DateEditor(fromDate, "dd-MM-yyyy"));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("To:");

        toDate.setModel(new javax.swing.SpinnerDateModel());
        toDate.setEditor(new javax.swing.JSpinner.DateEditor(toDate, "dd-MM-yyyy"));

        rangeButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        rangeButton.setText("Range");
        rangeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rangeButtonMouseClicked(evt);
            }
        });
        rangeButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rangeButtonKeyPressed(evt);
            }
        });

        transactionAll.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        transactionAll.setText("All");
        transactionAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionAllMouseClicked(evt);
            }
        });
        transactionAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                transactionAllKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout transactionsPanelLayout = new javax.swing.GroupLayout(transactionsPanel);
        transactionsPanel.setLayout(transactionsPanelLayout);
        transactionsPanelLayout.setHorizontalGroup(
            transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionsPanelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transactionsPanelLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPanelLayout.createSequentialGroup()
                                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(todayButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(transactionAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addComponent(MonthButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transactionsPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        transactionsPanelLayout.setVerticalGroup(
            transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(transactionAll)
                .addGap(26, 26, 26)
                .addComponent(todayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MonthButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(transactionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPanelLayout.createSequentialGroup()
                        .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)))
                .addComponent(rangeButton)
                .addContainerGap())
        );

        queryReport.add(transactionsPanel, java.awt.BorderLayout.WEST);

        clientViewPanel.setBackground(java.awt.Color.darkGray);
        clientViewPanel.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 2, true));
        clientViewPanel.setMaximumSize(new java.awt.Dimension(675, 32767));
        clientViewPanel.setMinimumSize(new java.awt.Dimension(650, 480));
        clientViewPanel.setPreferredSize(new java.awt.Dimension(675, 480));
        clientViewPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientViewPanelMouseClicked(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientWise.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Client :");

        clientList.setMinimumSize(new java.awt.Dimension(300, 27));
        clientList.setPreferredSize(new java.awt.Dimension(300, 27));

        clientAll.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        clientAll.setText("All");
        clientAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientAllMouseClicked(evt);
            }
        });
        clientAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clientAllKeyPressed(evt);
            }
        });

        clientTodayButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        clientTodayButton.setText("Today ");
        clientTodayButton.setMinimumSize(new java.awt.Dimension(200, 29));
        clientTodayButton.setPreferredSize(new java.awt.Dimension(200, 29));
        clientTodayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTodayButtonMouseClicked(evt);
            }
        });
        clientTodayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientTodayButtonActionPerformed(evt);
            }
        });
        clientTodayButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clientTodayButtonKeyPressed(evt);
            }
        });

        clientMonthButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        clientMonthButton.setText("Month ");
        clientMonthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientMonthButtonMouseClicked(evt);
            }
        });
        clientMonthButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clientMonthButtonKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("From :");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("To:");

        clientRangeButton.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        clientRangeButton.setText("Range");
        clientRangeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientRangeButtonMouseClicked(evt);
            }
        });
        clientRangeButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clientRangeButtonKeyPressed(evt);
            }
        });

        toDate2.setModel(new javax.swing.SpinnerDateModel());
        toDate2.setEditor(new javax.swing.JSpinner.DateEditor(toDate2, "dd-MM-yyy"));

        fromDate2.setModel(new javax.swing.SpinnerDateModel());
        fromDate2.setEditor(new javax.swing.JSpinner.DateEditor(fromDate2, "dd-MM-yyyy"));
        fromDate2.setName("fromDate2"); // NOI18N

        javax.swing.GroupLayout clientViewPanelLayout = new javax.swing.GroupLayout(clientViewPanel);
        clientViewPanel.setLayout(clientViewPanelLayout);
        clientViewPanelLayout.setHorizontalGroup(
            clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(clientViewPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(clientViewPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientViewPanelLayout.createSequentialGroup()
                        .addGroup(clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientRangeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(toDate2)
                            .addComponent(fromDate2)))
                    .addGroup(clientViewPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientViewPanelLayout.createSequentialGroup()
                                .addGroup(clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientTodayButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clientAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addComponent(clientMonthButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clientViewPanelLayout.setVerticalGroup(
            clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientViewPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(clientList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(clientAll)
                .addGap(26, 26, 26)
                .addComponent(clientTodayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clientMonthButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fromDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(toDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(clientRangeButton)
                .addGap(7, 7, 7))
        );

        queryReport.add(clientViewPanel, java.awt.BorderLayout.CENTER);

        add(queryReport, "queryCard");
    }// </editor-fold>//GEN-END:initComponents

 void resetLayout()
 {
     ((CardLayout)(this.getLayout())).show(this,"queryCard");
 }
         
 String getSelectedItemId()
 {
     String id =  null;
     if(clientList.getSelectedIndex() !=-1)
        {
                
            String selectedItem = clientList.getSelectedItem().toString();
            id = selectedItem.substring(selectedItem.lastIndexOf(")")+2);
        }
     return id;
 }
void clientToday()
    {
        String id = getSelectedItemId();
        if(id != null)
        {
            report = new ClientReport();
            report.showReport(id,"today");
            this.add("report", report);
            ((CardLayout)(this.getLayout())).show(this,"report");
        }
             
        
   }
    void clientMonth()
    {
        String id = getSelectedItemId();
        if(id != null)
        {
            report = new ClientReport();
            report.showReport(id,"monthly");
            this.add("report", report);
            ((CardLayout)(this.getLayout())).show(this,"report");
        }
                
    }
    
    
    
    void clientRange()
    {
        java.util.Date from = (Date)fromDate2.getValue();
        java.util.Date to = (Date)toDate2.getValue();
        
        String id = getSelectedItemId();
        if(id != null)
        {
             if(from.compareTo(to) <=0)
            {
                report = new ClientReport();
                report.showReport(id,from,to);
                this.add("report", report);
                ((CardLayout)(this.getLayout())).show(this,"report");

            }
        }
       
    }
    
    void clientAll()
    {
        String id = getSelectedItemId();
        if(id != null)
        {
            report = new ClientReport();
            report.showReport(id,"all");
            this.add("report", report);
            ((CardLayout)(this.getLayout())).show(this,"report");
        }
       
        
    }
    
    
 void transactionToday()
    {
        String id = getSelectedItemId();
        if(id != null)
        {
            report1 = new Report();
            report1.showReport("today");
            this.add("report", report1);
            ((CardLayout)(this.getLayout())).show(this,"report");
        }
             
        
   }
    void transactionMonth()
    {
        String id = getSelectedItemId();
        if(id != null)
        {
            report1 = new Report();
            report1.showReport("monthly");
            this.add("report", report1);
            ((CardLayout)(this.getLayout())).show(this,"report");
        }
                
    }
    
    void transactionRange()
    {
        java.util.Date from = (Date)fromDate.getValue();
        java.util.Date to = (Date)toDate.getValue();
        
        String id = getSelectedItemId();
        if(id != null)
        {
             if(from.compareTo(to) <=0)
            {

                report1 = new Report();
                report1.showReport(from,to);
                this.add("report", report1);
                ((CardLayout)(this.getLayout())).show(this,"report");

            }
        }
       
    }
    
    void transactionAll()
    {
        String id = getSelectedItemId();
        if(id != null)
        {
            report1 = new Report();
            report1.showReport("all");
            this.add("report", report1);
            ((CardLayout)(this.getLayout())).show(this,"report");
        }
        
    }
   
    private void todayButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_todayButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        transactionToday();
    }//GEN-LAST:event_todayButtonKeyPressed

    private void MonthButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MonthButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        transactionMonth();
    }//GEN-LAST:event_MonthButtonKeyPressed

    private void rangeButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rangeButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        transactionRange();
    }//GEN-LAST:event_rangeButtonKeyPressed

    
            
    private void transactionAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transactionAllKeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode() == KeyEvent.VK_ENTER)
          transactionAll(); 
    }//GEN-LAST:event_transactionAllKeyPressed

    private void clientAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientAllKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
          clientAll(); 
    }//GEN-LAST:event_clientAllKeyPressed

    private void clientTodayButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientTodayButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
          clientToday(); 
    }//GEN-LAST:event_clientTodayButtonKeyPressed

    private void clientMonthButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientMonthButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
          clientMonth();
    }//GEN-LAST:event_clientMonthButtonKeyPressed

    private void clientRangeButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientRangeButtonKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
          clientRange(); 
    }//GEN-LAST:event_clientRangeButtonKeyPressed

    private void transactionAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionAllMouseClicked
        // TODO add your handling code here:
        transactionAll();
    }//GEN-LAST:event_transactionAllMouseClicked

    private void todayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayButtonMouseClicked
        // TODO add your handling code here:
        transactionToday();
    }//GEN-LAST:event_todayButtonMouseClicked

    private void MonthButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonthButtonMouseClicked
        // TODO add your handling code here:
        transactionMonth();
    }//GEN-LAST:event_MonthButtonMouseClicked

    private void rangeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rangeButtonMouseClicked
        // TODO add your handling code here:
        transactionRange();
    }//GEN-LAST:event_rangeButtonMouseClicked

    private void clientAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientAllMouseClicked
        // TODO add your handling code here:
        clientAll(); 
    }//GEN-LAST:event_clientAllMouseClicked

    private void clientTodayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTodayButtonMouseClicked
        // TODO add your handling code here:
        clientToday();
    }//GEN-LAST:event_clientTodayButtonMouseClicked

    private void clientMonthButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientMonthButtonMouseClicked
        // TODO add your handling code here:
        clientMonth();
    }//GEN-LAST:event_clientMonthButtonMouseClicked

    private void clientRangeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientRangeButtonMouseClicked
        // TODO add your handling code here:
        clientRange(); 
    }//GEN-LAST:event_clientRangeButtonMouseClicked

    private void transactionsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionsPanelMouseClicked
        // TODO add your handling code here:
        transactionAll.requestFocus();
    }//GEN-LAST:event_transactionsPanelMouseClicked

    private void clientViewPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientViewPanelMouseClicked
        // TODO add your handling code here:
        clientAll.requestFocus();
    }//GEN-LAST:event_clientViewPanelMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        todayButton.requestFocus();
    }//GEN-LAST:event_formFocusGained

    private void MonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthButtonActionPerformed

    private void clientTodayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientTodayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientTodayButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MonthButton;
    private javax.swing.JButton clientAll;
    private javax.swing.JComboBox clientList;
    private javax.swing.JButton clientMonthButton;
    private javax.swing.JButton clientRangeButton;
    private javax.swing.JButton clientTodayButton;
    private javax.swing.JPanel clientViewPanel;
    private javax.swing.JSpinner fromDate;
    private javax.swing.JSpinner fromDate2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel queryReport;
    private javax.swing.JButton rangeButton;
    private javax.swing.JSpinner toDate;
    private javax.swing.JSpinner toDate2;
    private javax.swing.JButton todayButton;
    protected javax.swing.JButton transactionAll;
    private javax.swing.JPanel transactionsPanel;
    // End of variables declaration//GEN-END:variables
}
